// <auto-generated />
using System;
using AdSet.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdSet.Data.Migrations
{
    [DbContext(typeof(AdSetContext))]
    partial class AdSetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdSet.Domain.Entities.Optional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Optionals", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ar Condicionado"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Alarme"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Airbag"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Freio ABS"
                        });
                });

            modelBuilder.Entity("AdSet.Domain.Entities.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Packages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bronze"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Diamante"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Platinum"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Básico"
                        });
                });

            modelBuilder.Entity("AdSet.Domain.Entities.Portal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Portals", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "iCarros"
                        },
                        new
                        {
                            Id = 2,
                            Name = "WebMotors"
                        });
                });

            modelBuilder.Entity("AdSet.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("Km")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicle", (string)null);
                });

            modelBuilder.Entity("AdSet.Domain.Entities.VehicleImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleImages", (string)null);
                });

            modelBuilder.Entity("AdSet.Domain.Entities.VehicleOptional", b =>
                {
                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<int>("OptionalId")
                        .HasColumnType("int");

                    b.HasKey("VehicleId", "OptionalId");

                    b.HasIndex("OptionalId");

                    b.ToTable("VehicleOptionals", (string)null);
                });

            modelBuilder.Entity("AdSet.Domain.Entities.VehiclePortalPackage", b =>
                {
                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<int>("PortalId")
                        .HasColumnType("int");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.HasKey("VehicleId", "PortalId");

                    b.HasIndex("PackageId");

                    b.HasIndex("PortalId");

                    b.ToTable("VehiclePortalPackages", (string)null);
                });

            modelBuilder.Entity("AdSet.Domain.Entities.VehicleImage", b =>
                {
                    b.HasOne("AdSet.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("VehicleImages")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AdSet.Domain.Entities.VehicleOptional", b =>
                {
                    b.HasOne("AdSet.Domain.Entities.Optional", "Optional")
                        .WithMany("VehicleOptionals")
                        .HasForeignKey("OptionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdSet.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("VehicleOptionals")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Optional");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AdSet.Domain.Entities.VehiclePortalPackage", b =>
                {
                    b.HasOne("AdSet.Domain.Entities.Package", "Package")
                        .WithMany("VehiclePortalPackages")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdSet.Domain.Entities.Portal", "Portal")
                        .WithMany("VehiclePortalPackages")
                        .HasForeignKey("PortalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdSet.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("VehiclePortalPackages")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("Portal");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AdSet.Domain.Entities.Optional", b =>
                {
                    b.Navigation("VehicleOptionals");
                });

            modelBuilder.Entity("AdSet.Domain.Entities.Package", b =>
                {
                    b.Navigation("VehiclePortalPackages");
                });

            modelBuilder.Entity("AdSet.Domain.Entities.Portal", b =>
                {
                    b.Navigation("VehiclePortalPackages");
                });

            modelBuilder.Entity("AdSet.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("VehicleImages");

                    b.Navigation("VehicleOptionals");

                    b.Navigation("VehiclePortalPackages");
                });
#pragma warning restore 612, 618
        }
    }
}
